### ISSUE TITLE
句向量链接失效了 能再发一份吗 感谢

### ISSUE THREAD

**Issue by zzzk-c** [Yearsflow/Bachelor_Graduation#1]

**Comment by Yearsflow** [comment]
句向量找不到了，但是项目可以直接运行，没有用句向量

**Comment by zzzk-c** [comment]
好的 感谢

在 2022-11-04 17:04:03，Yearsflow ***@***.***> 写道：


句向量找不到了，但是项目可以直接运行，没有用句向量

**Comment by zzzk-c** [comment]
requirements.txt里面的路径需要改动吗？比如argon2-cffi @ file:///opt/conda/conda-bld/argon2-cffi_1645000214183/workpip，我直接安装依赖会报错没有该文件夹，我的anaconda里面没有这些文件夹
